#!/usr/bin/env bash
#
#  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  ██████╗
#  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔════╝
#  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║
#  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║
#  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚██████╗
#  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝
#	- Alos5
#	- 
#	- 
#

## path
PATH="$HOME/.config/bspwm/scripts:$PATH"
workspaces() {
    name=1
    for monitor in $(bspc query -M); do
        bspc monitor "${monitor}" -n "$name" -d '1' '2' '3' '4' 
        ((name++))
    done
}
workspaces
bspc config window_gap                6
bspc config split_ratio               0.51
bspc config single_monocle            true
bspc config borderless_monocle        true
bspc config gapless_monocle           true

##
bspc config focus_follows_pointer     true
bspc config pointer_follows_focus     false
bspc config pointer_motion_interval   5
bspc config pointer_modifier          mod4
bspc config pointer_action1           move
bspc config pointer_action2           resize_side
bspc config pointer_action3           resize_corner

##
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a scratch sticky=on state=floating focus=on



# Set random wallpaper 
rice_dir="$HOME/.Wallpeper"
feh -z --no-fehbg --bg-fill "${rice_dir}"
# config picom
pidof -q picom || { picom --config "$HOME"/.config/picom/picom.conf & }
# Reload sxhkd daemon "map teclado"
sxhkd -c "$HOME"/.config/bspwm/sxhkdrc &

# Enable tapping for touchpad "click"  xinput list
#xinput set-prop "Elan Touchpad" "libinput Tapping Enabled" 1
# Configurar Elan Touchpad
xinput set-prop "Elan Touchpad" "libinput Tapping Enabled" 1
xinput set-prop "Elan Touchpad" "libinput Tapping Drag Enabled" 1
xinput set-prop "Elan Touchpad" "libinput Tapping Drag Lock Enabled" 0
xinput set-prop "Elan Touchpad" "libinput Tapping Button Mapping Enabled" 1 0
xinput set-prop "Elan Touchpad" "libinput Natural Scrolling Enabled" 0
xinput set-prop "Elan Touchpad" "libinput Disable While Typing Enabled" 1
xinput set-prop "Elan Touchpad" "libinput Scroll Method Enabled" 1 0 0
xinput set-prop "Elan Touchpad" "libinput Click Method Enabled" 1 0
xinput set-prop "Elan Touchpad" "libinput Middle Emulation Enabled" 0
xinput set-prop "Elan Touchpad" "libinput Accel Speed" 1.0
xinput set-prop "Elan Touchpad" "libinput Accel Profile Enabled" 0 1
xinput set-prop "Elan Touchpad" "libinput Left Handed Enabled" 0
xinput set-prop "Elan Touchpad" "libinput Send Events Mode Enabled" 0 0
xinput set-prop "Elan Touchpad" "libinput Horizontal Scroll Enabled" 1
xinput set-prop "Elan Touchpad" "libinput Scrolling Pixel Distance" 15
xinput set-prop "Elan Touchpad" "libinput High Resolution Wheel Scroll Enabled" 1
