#!/bin/sh

# Configurar Elan Touchpad
xinput set-prop "Elan Touchpad" "libinput Tapping Enabled" 1
xinput set-prop "Elan Touchpad" "libinput Tapping Drag Enabled" 1
xinput set-prop "Elan Touchpad" "libinput Tapping Drag Lock Enabled" 0
xinput set-prop "Elan Touchpad" "libinput Tapping Button Mapping Enabled" 1 0
xinput set-prop "Elan Touchpad" "libinput Natural Scrolling Enabled" 0
xinput set-prop "Elan Touchpad" "libinput Disable While Typing Enabled" 1
xinput set-prop "Elan Touchpad" "libinput Scroll Method Enabled" 1 0 0
xinput set-prop "Elan Touchpad" "libinput Click Method Enabled" 1 0
xinput set-prop "Elan Touchpad" "libinput Middle Emulation Enabled" 0
xinput set-prop "Elan Touchpad" "libinput Accel Speed" 1.0
xinput set-prop "Elan Touchpad" "libinput Accel Profile Enabled" 0 1
xinput set-prop "Elan Touchpad" "libinput Left Handed Enabled" 0
xinput set-prop "Elan Touchpad" "libinput Send Events Mode Enabled" 0 0
xinput set-prop "Elan Touchpad" "libinput Horizontal Scroll Enabled" 1
xinput set-prop "Elan Touchpad" "libinput Scrolling Pixel Distance" 15
xinput set-prop "Elan Touchpad" "libinput High Resolution Wheel Scroll Enabled" 1
